// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  backArrow: require('../Images/Icons/back-arrow.png'),
  danger: require('../Images/Icons/danger.png'),
  file: require('../Images/Icons/file.png'),
  ghost: require('../Images/Icons/ghost.png'),
  inclinedBell: require('../Images/Icons/inclined-bell.png'),
  person: require('../Images/Icons/person.png'),
  powerIcon: require('../Images/Icons/power-icon.png'),
  privacy: require('../Images/Icons/privacy.png'),
  rightArrow: require('../Images/Icons/rightArrow.png'),
  fbIcon: require('../Images/fbicon.png'),
  twitterIcon: require('../Images/twittericon.png'),
  snapchatIcon: require('../Images/snapchaticon.png'),
  igIcon: require('../Images/igicon.png')
}

export default images
