# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FriendThem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FriendThem

  pod 'Fabric'
  pod 'Crashlytics'

  target 'FriendThem-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  end

  target 'FriendThemTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FriendThem-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
